# Generated by Django 4.2.11 on 2024-05-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('genres', models.CharField(max_length=70)),
                ('year', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='movie_image')),
                ('movieduration', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(max_length=250, null=True)),
                ('actors', models.CharField(max_length=750, null=True)),
                ('trailer_link', models.URLField(max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=70)),
                ('rated_date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MovieRecommender.movie')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
